
#ifndef SUPER_MARIO_16X16_HPP_
#define SUPER_MARIO_16X16_HPP_

#include <iostream>

#define MARIO_SIZE 16

// colour definition:
// . : black
// W : white
// R : red
// B : blue
// b : brown
// O : orange
// G : green
// g : gray
// Y : yellow
// p : pink

static const uint8_t* mario = (uint8_t*)

//---------------------------- index = 0 : flower
".....WWWWWW....."
"...WWWWWWWWWW..."
"..WWWOOOOOOWWW.."
".WWOOORRRROOWWW."
".WWOOORRRROOWWW."
"..WWWOOOOOOWWW.."
"...WWWWWWWWWW..."
".....WWWWWW....."
".......GG......."
"GGG....GG....GGG"
".GGG...GG...GGG."
".GGGG..GG..GGGG."
"..GGGG.GG.GGGG.."
"..GGGG.GG.GGGG.."
"...GGGGGGGGGG..."
"......GGGG......"

//---------------------------- index = 1 : mushroom red
"......YYYY......"
".....YYYYRR....."
"....YYYYRRRR...."
"...YYYYYRRRRR..."
"..YYYYYYYRRRYY.."
".YYYRRRYYYYYYYY."
".YYRRRRRYYYYYYY."
"YYYRRRRRYYYYRRYY"
"YYYRRRRRYYYYRRRY"
"YYYYRRRYYYYYYRRY"
".YYYYYYYYYYYYYY."
"..YRRRWWWWWRRRY."
".....WWWWWWW...."
".....WWWWWOW...."
".....WWWWWOW...."
"......WWWOW....."

//---------------------------- index = 2 : mushroom green
"......YYYY......"
".....YYYYGG....."
"....YYYYGGGG...."
"...YYYYYGGGGG..."
"..YYYYYYYGGGYY.."
".YYYGGGYYYYYYYY."
".YYGGGGGYYYYYYY."
"YYYGGGGGYYYYGGYY"
"YYYGGGGGYYYYGGGY"
"YYYYGGGYYYYYYGGY"
".YYYYYYYYYYYYYY."
"..YGGGWWWWWGGGY."
".....WWWWWWW...."
".....WWWWWOW...."
".....WWWWWOW...."
"......WWWOW....."

//---------------------------- index = 3 : mushroom 2 red
"................"
"......RWWR......"
"....RRRWWRRR...."
"...WRRWWWWRRW..."
"..RWWWWWWWWWWR.."
"..RRWWRRRRWWRR.."
".RRRWRRRRRRWRRR."
".RRRWRRRRRRWRRR."
".RRRWRRRRRRWRRR."
".WWWWWRRRRWWWWW."
".WW..........WW."
"....WW.WW.WW...."
"...WWW.WW.WWW..."
"...WWWWWWWWWW..."
"....WWWWWWWW...."
"................"

//---------------------------- index = 4 : mushroom 2 green
"................"
"......GWWG......"
"....GGGWWGGG...."
"...WGGWWWWGGW..."
"..GWWWWWWWWWWG.."
"..GGWWGGGGWWGG.."
".GGGWGGGGGGWGGG."
".GGGWGGGGGGWGGG."
".GGGWGGGGGGWGGG."
".WWWWWGGGGWWWWW."
".WW..........WW."
"....WW.WW.WW...."
"...WWW.WW.WWW..."
"...WWWWWWWWWW..."
"....WWWWWWWW...."
"................"

//---------------------------- index = 5 : mushroom
"................"
".......YY......."
".......YY......."
"......YYYY......"
"......YYYY......"
"YYYYYYYYYYYYYYYY"
".YYYYY.YY.YYYYY."
"..YYYY.YY.YYYY.."
"...YYY.YY.YYY..."
"...YYYYYYYYYY..."
"...YYYYYYYYYY..."
"..YYYYYYYYYYYY.."
"..YYYYYYYYYYYY.."
".YYYYY....YYYYY."
".YYY........YYY."
"YY............YY"

//---------------------------- index = 6 : question box
".RRRRRRRRRRRRRR."
"RYYYYYYYYYYYYYYg"
"RY.YYYYYYYYYY.Yg"
"RYYYYRRRRRYYYYYg"
"RYYYRR...RRYYYYg"
"RYYYRR.YYRR.YYYg"
"RYYYRR.YYRR.YYYg"
"RYYYY..YRRR.YYYg"
"RYYYYYYRR...YYYg"
"RYYYYYYRR.YYYYYg"
"RYYYYYYY..YYYYYg"
"RYYYYYYRRYYYYYYg"
"RYYYYYYRR.YYYYYg"
"RY.YYYYY..YYY.Yg"
"RYYYYYYYYYYYYYYg"
".ggggggggggggggg"

//---------------------------- index = 7 : empty box
".gggggggggggggg."
"gRRRRRRRRRRRRRRg"
"gRgRRRRRRRRRRgRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRRRRRRRRRRRRRRg"
"gRgRRRRRRRRRRgRg"
"gRRRRRRRRRRRRRRg"
".gggggggggggggg."

//---------------------------- index = 8 : point
"................"
".....YYYYgg....."
"....YYYYYYgg...."
"....YYWWYYgg...."
"...YYWYYgYYgg..."
"...YYWYYgYYgg..."
"...YYWYYgYYgg..."
"...YYWYYgYYgg..."
"...YYWYYgYYgg..."
"...YYWYYgYYgg..."
"...YYWYYgYYgg..."
"...YYWYYgYYgg..."
"....YYggYYgg...."
"....YYYYYYgg...."
".....YYYYgg....."
"................"

//---------------------------- index = 9 : wall
"pppppppppppppppp"
"RRRRRRR.RRRRRRR."
"RRRRRRR.RRRRRRR."
"................"
"RRR.RRRRRRR.RRRR"
"RRR.RRRRRRR.RRRR"
"RRR.RRRRRRR.RRRR"
"................"
"RRRRRRR.RRRRRRR."
"RRRRRRR.RRRRRRR."
"RRRRRRR.RRRRRRR."
"................"
"RRR.RRRRRRR.RRRR"
"RRR.RRRRRRR.RRRR"
"RRR.RRRRRRR.RRRR"
"................"

//---------------------------- index = 10 : brick
"Rpppppppp.RppppR"
"pRRRRRRRR.pRRRR."
"pRRRRRRRR.pRRRR."
"pRRRRRRRR.pRRRR."
"pRRRRRRRR.p.RRR."
"pRRRRRRRR.R....R"
"pRRRRRRRR.ppppp."
"pRRRRRRRR.pRRRR."
"pRRRRRRRR.pRRRR."
"pRRRRRRRR.pRRRR."
"..RRRRRR.pRRRRR."
"pp..RRRR.pRRRRR."
"pRpp....pRRRRRR."
"pRRRppp.pRRRRRR."
"pRRRRRR.pRRRRR.."
"R.......p......R"

//---------------------------- index = 11 : flag
"..O............."
".OOO............"
"..O............."
"..RWWWWWWWWWWWW."
"..RWWWWWRWWWWWW."
"..RWWWWWRWWWWWW."
"..RWWRRRRRRRWWW."
"..RWWWRRRRRWWWW."
"..RWWWWRRRWWWWW."
"..RWWWRRWRRWWWW."
"..RWWWRWWWRWWWW."
"..RWWWWWWWWWWWW."
"..R............."
"..R............."
"..R............."
"..R............."

//---------------------------- index = 12 : fish right 1
".........OOOO..."
"....WW.OOOOO...."
"...WWWWgggggg..."
"...WWWWggggWWgW."
"...WWWWgggWWWWWW"
"...WWWWWggWWgWgW"
"....WWWWggWWgWgW"
"....gWWWggWWWWWW"
"....gggggggWWgW."
"....gggggggggOOO"
"O..gggggggggOOg."
"OOOggggggggOOg.."
"OOOggggggWWOOg.."
".OOOggggWWWOOOO."
".OOO.gWWWWWWWW.."
"..O....WWWWW...."

//---------------------------- index = 13 : fish right 2
".........OOOO..."
".......OOOOO...."
"......Ogggggg..."
"......gggggWWgW."
".WWWWgggggWWWWWW"
"WWWWWWggggWWgWgW"
"WWWWWWWgggWWgWgW"
".WWWWWWWggWWWWWW"
".WWWWWWWgggWWgW."
"O.gggggggggggOOO"
"OOggggggggggOOg."
"OOgggggggggOOg.."
".OgggggggWWOOg.."
".OOgggggWWWOOOO."
"..O.gWWWWWWWWW.."
".......WWWWW...."

//---------------------------- index = 14 : fish left 1
"...OOOO........."
"....OOOOO.WW...."
"...ggggggWWWW..."
".WgWWggggWWWW..."
"WWWWWWgggWWWW..."
"WgWgWWggWWWWW..."
"WgWgWWggWWWW...."
"WWWWWWggWWWg...."
".WgWWggggggg...."
"OOOggggggggg...."
".gOOggggggggg..O"
"..gOOggggggggOOO"
"..gOOWWggggggOOO"
".OOOOWWWggggOOO."
"..WWWWWWWWg.OOO."
"....WWWWW....O.."

//---------------------------- index = 15 : fish left 2
"...OOOO........."
"....OOOOO......."
"...ggggggO......"
".WgWWggggg......"
"WWWWWWgggggWWWW."
"WgWgWWggggWWWWWW"
"WgWgWWgggWWWWWWW"
"WWWWWWggWWWWWWW."
".WgWWgggWWWWWWW."
"OOOggggggggggg.O"
".gOOggggggggggOO"
"..gOOgggggggggOO"
"..gOOWWgggggggO."
".OOOOWWWgggggOO."
"..WWWWWWWWWg.O.."
"....WWWWW......."

//---------------------------- index = 16 : iron turtle right 1
"......ggg......."
"....gggggggg...."
"...gggggggggg..."
"..gggGGggggggg.."
"..ggGpGgggggggg."
"..ggGGggggggggg."
".gggggggggggGGGG"
".ggggggggggGGgg."
".ggggggggggGggg."
".ggggggggggGgpgg"
".ggggggggggGgggg"
".ggggggggggGgggg"
"GGGGGgggggGGpgg."
"..ppGGGggGGpp..."
"..ppp.GGGGppp..."
"...pp.....pp...."

//---------------------------- index = 17 : iron turtle right 2
"................"
"......gggg......"
"....gggggggg...."
"...gggggggggg..."
"..gggGGggggggg.."
"..ggGpGgggggggg."
"..ggGGggggggggg."
".gggggggggggGGGG"
".ggggggggggGGgg."
".ggggggggggGggg."
".ggggggggggGgpgg"
".ggggggggggGgggg"
".ggggggggggGgggg"
"GGGGGgggggGGpgg."
".pppGGGggGGppp.."
"pppp..GGGG.pppp."

//---------------------------- index = 18 : iron turtle left 1
".......ggg......"
"....gggggggg...."
"...gggggggggg..."
"..gggggggGGggg.."
".ggggggggGpGgg.."
".gggggggggGGgg.."
"GGGGggggggggggg."
".ggGGgggggggggg."
".gggGgggggggggg."
"ggpgGgggggggggg."
"ggggGgggggggggg."
"ggggGgggggggggg."
".ggpGGgggggGGGGG"
"...ppGGggGGGpp.."
"...pppGGGG.ppp.."
"....pp.....pp..."

//---------------------------- index = 19 : iron turtle left 2
"................"
"......gggg......"
"....gggggggg...."
"...gggggggggg..."
"..gggggggGGggg.."
".ggggggggGpGgg.."
".gggggggggGGgg.."
"GGGGggggggggggg."
".ggGGgggggggggg."
".gggGgggggggggg."
"ggpgGgggggggggg."
"ggggGgggggggggg."
"ggggGgggggggggg."
".ggpGGgggggGGGGG"
"..pppGGggGGGppp."
".pppp.GGGG..pppp"


//---------------------------- index = 20 : monster right
"......RRRR......"
".....RRRRRR....."
"....RRRRRRRR...."
"...RRRRRRRRRR..."
"..RggRRRRRRggR.."
".RRRWgRRRRgWRRR."
".RRRWggggggWRRR."
"RRRRWgWRRWgWRRRR"
"RRRRWWWRRWWWRRRR"
"RRRRRRRRRRRRRRRR"
".RRRRWWWWWWRRRR."
"....WWWWWWWW...."
"....WWWWWWWWgg.."
"...ggWWWWWggggg."
"...gggWWWgggggg."
"....ggg..ggggg.."

//---------------------------- index = 21 : monster left
"......RRRR......"
".....RRRRRR....."
"....RRRRRRRR...."
"...RRRRRRRRRR..."
"..RggRRRRRRggR.."
".RRRWgRRRRgWRRR."
".RRRWggggggWRRR."
"RRRRWgWRRWgWRRRR"
"RRRRWWWRRWWWRRRR"
"RRRRRRRRRRRRRRRR"
".RRRRWWWWWWRRRR."
"....WWWWWWWW...."
"..ggWWWWWWWW...."
".gggggWWWWWgg..."
".ggggggWWWggg..."
"..ggggg..ggg...."

//---------------------------- index = 22 : spike turtle right 1

"................"
".......W........"
".......W........"
"......OOW......."
".W....OOW....W.."
".OW..OOOOW..OW.."
".OOW.OOOOW.OOW.."
".OOOWROOOROOOW.."
".OOOWRRRRROOWW.."
".ROORROWWRROORR."
".RRRROOOWWRRRWWW"
"RRRRROOOOORRWRR."
"WWWRRROOORRWRRWR"
"..WWWRRRRRWORRRR"
".OOOWWWWWWOOO..."
"OOOO......OOOO.."

//---------------------------- index = 23 : spike turtle right 2
".......W........"
".......W........"
"......OOW......."
".W....OOW....W.."
".OW..OOOOW..OW.."
".OOW.OOOOW.OOW.."
".OOOWROOOROOOW.."
".OOOWRRRRROOWW.."
".ROORROWWRROORR."
".RRRROOOWWRRRWWW"
"RRRRROOOOORRWRR."
"WWWRRROOORRWRRWR"
"..WWWRRRRRWORRRR"
"..OOWWWWWWOOO..."
"...OOO...OOO...."
"....OO...OO....."

//---------------------------- index = 24 : spike turtle left 1
"................"
"........W......."
"........W......."
".......WOO......"
"..W....WOO....W."
"..WO..WOOOO..WO."
"..WOO.WOOOO.WOO."
"..WOOOROOORWOOO."
"..WWOORRRRRWOOO."
".RROORRWWORROOR."
"WWWRRRWWOOORRRR."
".RRWRROOOOORRRRR"
"RWRRWRROOORRRWWW"
"RRRROWRRRRRWWW.."
"...OOOWWWWWWOOO."
"..OOOO......OOOO"

//---------------------------- index = 25 : spike turtle left 2
"........W......."
"........W......."
".......WOO......"
"..W....WOO....W."
"..WO..WOOOO..WO."
"..WOO.WOOOO.WOO."
"..WOOOROOORWOOO."
"..WWOORRRRRWOOO."
".RROORRWWORROOR."
"WWWRRRWWOOORRRR."
".RRWRROOOOORRRRR"
"RWRRWRROOORRRWWW"
"RRRROWRRRRRWWW.."
"...OOOWWWWWWOO.."
"....OOO...OOO..."
".....OO...OO...."

//---------------------------- index = 26 : mario right 1
"................"
".....RRRRR......"
"....RRRRRRRRR..."
"....bbbOObO....."
"...bObOOObOOO..."
"...bObbOOObOOO.."
"...bbOOOObbbb..."
".....OOOOOOO...."
"....bbbRbb......"
"...bbbbRRbb....."
"...bbbRRORR....."
"...bbbbRRRR....."
"...bbbOORRR....."
"....RbOORR......"
".....RRRbbb....."
".....bbbb......."

//---------------------------- index = 27 : mario right 2
".....RRRRR......"
"....RRRRRRRRR..."
"....bbbOObO....."
"...bObOOObOOO..."
"...bObbOOObOOO.."
"...bbOOOObbbb..."
".....OOOOOOO...."
"......bbRRb....."
".....bbbbRbOO..."
"...OObbbbbbOOO.."
"..OOORbbbbbOO..."
"...bbRRRRRRR...."
"...bRRRRRRRR...."
"..bbRR..RRR....."
"..b....bbb......"
"........bbb....."

//---------------------------- index = 28 : mario right 3
".....RRRRR......"
"....RRRRRRRRR..."
"....bbbOObO....."
"...bObOOObOOO..."
"...bObbOOObOOO.."
"...bbOOOObbbb..."
".....OOOOOOO...."
"...bbbRbbbR....."
".OObbbRRbbbRbOOO"
".OO.bbRRRRRRbbOO"
".O..RRRORRRO..b."
"...RRRRRRRRRRbb."
"..RRRRRRRRRRRbb."
".bbRRR....RRRbb."
".bbb............"
"..bbb..........."


//---------------------------- index = 29 : mario left 1
"................"
"......RRRRR....."
"...RRRRRRRRR...."
".....ObOObbb...."
"...OOObOOObOb..."
"..OOObOOObbOb..."
"...bbbbOOOObb..."
"....OOOOOOO....."
"......bbRbbb...."
".....bbRRbbbb..."
".....RRORRbbb..."
".....RRRRbbbb..."
".....RRROObbb..."
"......RROObR...."
".....bbbRRR....."
".......bbbb....."

//---------------------------- index = 30 : mario left 2
"......RRRRR....."
"...RRRRRRRRR...."
".....ObOObbb...."
"...OOObOOObOb..."
"..OOObOOObbOb..."
"...bbbbOOOObb..."
"....OOOOOOO....."
".....bRRbb......"
"...OObRbbbb....."
"..OOObbbbbbOO..."
"...OObbbbbROOO.."
"....RRRRRRRbb..."
"....RRRRRRRRb..."
".....RRR..RRbb.."
"......bbb....b.."
".....bbb........"

//---------------------------- index = 31 : mario left 3
"......RRRRR....."
"...RRRRRRRRR...."
".....ObOObbb...."
"...OOObOOObOb..."
"..OOObOOObbOb..."
"...bbbbOOOObb..."
"....OOOOOOO....."
".....RbbbRbbbb.."
"OOObRbbbRRbbbOO."
"OObbRRRRRRbb.OO."
".b..ORRRORRR..O."
".bbRRRRRRRRRR..."
".bbRRRRRRRRRRR.."
".bbRRR....RRRbb."
"............bbb."
"...........bbb.."
;

#endif

